apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: host-data
          mountPath: /host-data
          readOnly: false
  volumes:
    - name: host-data
      hostPath:
        path: /tmp
        type: Directory